//! Footprint baseline — the single committed record of the measured footprint
//! of every stable public type, plus the per-connection resident estimate and
//! the minimum-consumer binary size at the time of measurement.
//!
//! The per-type pins live co-located with each type as `footprint_pin!`
//! (`const _: ()`, an `E0080` build failure on drift). This test is the
//! *human-readable ledger*: it re-asserts the same numbers from one place so a
//! reviewer can see the whole footprint surface at a glance, and it records the
//! per-connection resident estimate — the one number that is NOT a single
//! type's `size_of` — so future drift is comparable.
//!
//! All numbers measured @ aarch64-apple-darwin, rustc 1.96.0.
//!
//! If a stable public type's size legitimately changes, BOTH its co-located
//! `footprint_pin!` and the matching line here move in the same commit — that
//! is the point: the byte cost lands on the review surface, never drifting
//! silently.
//!
//! # Runtime footprint has teeth elsewhere; binary size is a documented anchor
//!
//! The MEANINGFUL footprint regression gate is now **runtime peak RSS**, not a
//! static binary-size number: the `bench` branch's `rss_ceiling` test runs a
//! real 10k-SELECT + 1k-INSERT workload over one connection and fails if the
//! blocking driver's peak resident set exceeds 2 MiB (measured ≈ 1.7 MiB) — a
//! number bsql actually controls.
//!
//! The **minimum-consumer binary size** is recorded here as documentation only,
//! deliberately NOT gated: measured by building a minimal SQLite-only consumer
//! (`open_in_memory` + `execute` + `query`) in release and stripping it, it was
//! **≈ 2.03 MB** (aarch64-apple-darwin, rustc 1.96.0). That figure is dominated
//! by the **bundled SQLite C engine** `rusqlite` statically links, NOT by bsql's
//! own Rust code — so a binary-size ceiling would gate a third party's C
//! amalgamation, not bsql, and would be platform- and linker-variable. It is an
//! anchor for comparison, regenerated by re-building and stripping a minimal
//! consumer; the runtime RSS gate is what defends bsql's footprint.

use core::mem::{align_of, size_of};

use bsql_postgres_core::{
    ArenaSealError, ConnectConfig, DbError, DriverError, Notification, QueryResult, Row, RowSet,
    SslMode,
};

/// `(size, align)` baseline for every stable public type of `bsql-postgres-core`.
/// This mirrors the co-located `footprint_pin!` anchors; a divergence between
/// the two means one was edited without the other.
#[test]
fn core_stable_public_types_match_baseline() {
    // (measured size, measured align, expected size, expected align, name)
    let rows: &[(usize, usize, usize, usize, &str)] = &[
        (size_of::<Row>(), align_of::<Row>(), 16, 8, "Row"),
        (size_of::<ArenaSealError>(), align_of::<ArenaSealError>(), 1, 1, "ArenaSealError"),
        (size_of::<DriverError>(), align_of::<DriverError>(), 24, 8, "DriverError"),
        (size_of::<DbError>(), align_of::<DbError>(), 104, 8, "DbError"),
        (size_of::<ConnectConfig>(), align_of::<ConnectConfig>(), 152, 8, "ConnectConfig"),
        (size_of::<SslMode>(), align_of::<SslMode>(), 1, 1, "SslMode"),
        (size_of::<Notification>(), align_of::<Notification>(), 56, 8, "Notification"),
        (size_of::<RowSet>(), align_of::<RowSet>(), 16, 8, "RowSet"),
        (size_of::<QueryResult>(), align_of::<QueryResult>(), 72, 8, "QueryResult"),
    ];
    for &(sz, al, exp_sz, exp_al, name) in rows {
        assert_eq!(sz, exp_sz, "footprint baseline drift (size) for {name}");
        assert_eq!(al, exp_al, "footprint baseline drift (align) for {name}");
    }
}

/// Per-connection resident footprint anchor.
///
/// The dominant heap component a single open PostgreSQL connection holds,
/// excluding the OS-kernel socket buffers (which the driver does not allocate),
/// is the engine's read buffer — a fixed `READ_BUF_CAP`-byte allocation made
/// once per connection. The constant is pinned in `bsql-postgres-proto`; this
/// re-asserts it from the consumer side so a tuning change lands on the review
/// surface here too.
#[test]
fn per_connection_resident_estimate() {
    // The read buffer is a fixed 4 KiB allocation made once per connection.
    assert_eq!(
        bsql_postgres_proto::READ_BUF_CAP, 4096,
        "per-connection read buffer size changed; update the resident estimate"
    );
}

// The minimum-consumer binary size (≈ 2.03 MB, SQLite-dominated) is recorded in
// the module doc above as a documentation anchor, NOT as a test: a test that
// asserts nothing defends no invariant. The footprint number that bsql controls
// and that regresses meaningfully is runtime peak RSS, gated by the `bench`
// branch's `rss_ceiling` test.
