//! MD5-password authentication helpers — DEF-216 (2026-05-05).
//!
//! Encapsulates the cryptographic primitives + memory-hygiene
//! discipline for PG's `AuthenticationMD5Password` (sub-code 5)
//! handshake. Keeps the crypto surface in one auditable module.
//!
//! # Algorithm (PG §55.4 "MD5 password authentication")
//!
//! Server sends `AuthenticationMD5Password` with a 4-byte salt.
//! Client responds with `PasswordMessage` body =
//! `"md5" || md5_hex(md5_hex(password || username) || raw_salt)`,
//! where `md5_hex` produces 32 lowercase ASCII hex characters.
//!
//! # Security profile
//!
//! MD5 is cryptographically broken for collision-resistant uses
//! and offline GPU cracking of MD5-salted passwords is fast in
//! 2025 dollars-per-hash terms. PG's auth protocol DOES NOT depend
//! on collision resistance; the salt+rehash protects only against
//! passive on-wire observation by an attacker who lacks
//! offline-cracking compute. This module exists for legacy
//! compatibility with on-prem PG ≤ 13 deployments. The driver
//! wrapper (Phase 1e) is responsible for warning operators on
//! cleartext-equivalent auth methods and preferring SCRAM where
//! the server offers it.
//!
//! # Memory hygiene
//!
//! Every intermediate buffer that contains password-derived bytes
//! (the `password || username` concatenation, the inner digest,
//! the inner-hex string, the outer concatenation) is wrapped in
//! [`zeroize::Zeroizing`] so the memory is scrubbed on Drop. The
//! `md-5` library itself does not retain the input after `update`
//! (RustCrypto's `Digest` trait drops the internal state on
//! `finalize`).
//!
//! # CREDO §11 audit-trust
//!
//! Uses `md-5` from RustCrypto (audited, 1M+ downloads/month,
//! sibling to existing `sha2`/`hmac`/`pbkdf2` deps). Hand-rolled
//! MD5 is forbidden per DEF-META-01 policy 9 (never hand-roll
//! expert-domain code), even though MD5's algorithm is fully
//! documented and could be implemented in <200 LoC — the risk is
//! drift between our implementation and the spec, not the
//! algorithmic weakness (which is the protocol's, not ours).

use crate::password::Password;
use crate::sensitive::Sensitive;
use md5::{Digest, Md5};
use zeroize::Zeroizing;

/// Bundled MD5-handshake state — username + password — carried
/// inside [`crate::state::ProtoState::ConnectingStartupMd5`] via a
/// single `Box`. DEF-216 (2026-05-05); mirrors the SCRAM PERF-02
/// single-Box pattern.
///
/// # Drop chain
///
/// `Md5HandshakeState::drop` is auto-generated by the compiler
/// (no explicit derive needed). It drops fields in declaration
/// order:
///
/// 1. `password: Sensitive<Password>` — drops via
///    `Sensitive::drop` → `Password::drop` (`ZeroizeOnDrop`),
///    scrubbing the 512-byte password buffer.
/// 2. `user: crate::ident::Ident` — drops trivially (POD bytes,
///    not secret; the username travelled cleartext in
///    `StartupMessage`).
///
/// Wrapped in `Box`, the entire chain fires on `Box::drop` at the
/// state-transition site that consumes the variant.
/// `pub` keyword required to silence `private_interfaces` lint
/// (the type is named in `pub enum ProtoState`'s variant). The
/// containing module is `pub(crate)` so effective visibility from
/// outside the crate stays sealed: external users cannot reach
/// the type name `bsql_pg_proto::md5::Md5HandshakeState` — the
/// path resolves through a `pub(crate) mod md5;` barrier. Mirror
/// of the SCRAM pattern (`pub struct ScramSession` inside
/// `pub mod scram` with internal fields `pub(crate)`).
#[derive(Debug)]
pub struct Md5HandshakeState {
    /// Password sensitive bytes. ZeroizeOnDrop chain via
    /// `Sensitive::drop` → `Password::drop`.
    pub(crate) password: Sensitive<Password>,
    /// Username from the `StartupMessage`. Non-secret (cleartext on
    /// wire); not zeroized.
    pub(crate) user: crate::ident::Ident,
}

/// Compute the MD5 password digest per PG §55.4 and write the
/// 35-byte response body (`"md5" + 32 hex chars`) into `out`.
///
/// # Inputs
///
/// - `password`: the user's password bytes.
/// - `username`: the username (UTF-8 bytes from `Ident`).
/// - `salt`: the 4-byte salt extracted from
///   `AuthenticationMD5Password`.
///
/// # Output
///
/// `out: &mut [u8; 35]` is filled with the bytes the wire frame's
/// length-prefixed body should carry (excluding the trailing NUL,
/// which the caller appends).
///
/// # Memory hygiene
///
/// Three `Zeroizing` buffers hold password-derived intermediates:
/// the `password || username` concatenation, the inner hex string,
/// and the `inner_hex || salt` concatenation. All scrub on Drop at
/// function return.
pub(crate) fn compute_response_body(
    password: &Password,
    username: &[u8],
    salt: [u8; 4],
    out: &mut [u8; 35],
) {
    // Step 1: inner_digest = MD5(password || username).
    //
    // Build the concatenation in a heap-allocated `Zeroizing<Vec<u8>>`
    // so it scrubs on drop. Stack would also work but `Vec` is the
    // simplest path that handles arbitrary password length up to
    // MAX_PASSWORD_LEN (512 B) + max ident length without a static
    // array sized for the worst case.
    //
    // No-alloc note: this is the cold auth path (handshake-time
    // only, ~once per connection). Allocation is acceptable per
    // the same audit-trust position as SCRAM's heapless::Vec
    // intermediates in `scram::wire`.
    let mut hasher = Md5::new();
    hasher.update(password.as_bytes());
    hasher.update(username);
    // `Output<Md5>` is a `GenericArray<u8, U16>`. Wrap in Zeroizing
    // so the 16-byte digest scrubs on drop.
    let inner_digest: Zeroizing<[u8; 16]> = Zeroizing::new(hasher.finalize().into());

    // Step 2: inner_hex = lowercase_hex(inner_digest) — 32 ASCII chars.
    let mut inner_hex: Zeroizing<[u8; 32]> = Zeroizing::new([0u8; 32]);
    write_hex_lowercase(&inner_digest, &mut inner_hex);

    // Step 3: outer_digest = MD5(inner_hex || salt).
    let mut outer_hasher = Md5::new();
    outer_hasher.update(inner_hex.as_slice());
    outer_hasher.update(salt);
    // The outer digest is NOT secret in the same way: it goes on
    // the wire as the response. But it's password-derived and
    // wrapping in Zeroizing for the brief window before it's
    // copied to `out` is cheap defence-in-depth.
    let outer_digest: Zeroizing<[u8; 16]> = Zeroizing::new(outer_hasher.finalize().into());

    // Step 4: build "md5" || lowercase_hex(outer_digest) into `out`.
    // The first 3 bytes are the literal "md5".
    let prefix = b"md5";
    if let Some(slot) = out.get_mut(..3) {
        slot.copy_from_slice(prefix);
    }
    // The remaining 32 bytes hold the hex-encoded outer digest.
    // Use a `Zeroizing<[u8; 32]>` intermediate so that — even
    // though `outer_hex` content is what we send on the wire and
    // is therefore not "more secret" than the response itself —
    // the local stack copy scrubs on drop. Defence in depth: a
    // future caller that retains `out` longer than the dispatch
    // path expects will still see no lingering hex bytes in this
    // function's stack frame after return.
    let mut outer_hex: Zeroizing<[u8; 32]> = Zeroizing::new([0u8; 32]);
    write_hex_lowercase(&outer_digest, &mut outer_hex);
    if let Some(hex_slot) = out.get_mut(3..35) {
        hex_slot.copy_from_slice(outer_hex.as_slice());
    }
}

/// Write 16 input bytes as 32 lowercase ASCII hex characters into
/// `out`. Branchless per-nibble lookup via a small lookup table.
///
/// # Safety / correctness
///
/// - Indexing is bounded by construction: `i` ranges 0..16 and
///   `out` is sized [u8; 32]; offsets `i*2` and `i*2+1` are
///   always in-bounds.
/// - The hex table is a `const &[u8; 16]`; lookups via `.get()`
///   with `unwrap_or(b'?')` provide a fallback that is
///   architecturally unreachable (the nibble masks below produce
///   values in 0..=15).
fn write_hex_lowercase(input: &[u8; 16], out: &mut [u8; 32]) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for (i, byte) in input.iter().enumerate() {
        let hi = usize::from(byte >> 4);
        let lo = usize::from(byte & 0x0f);
        // .get() returns Option<&u8>; .copied() unwraps Some(u8);
        // unwrap_or fires only on out-of-range nibble (impossible
        // under the masks above) — `b'?'` is the sentinel a future
        // bug would surface as.
        let hi_char = HEX.get(hi).copied().unwrap_or(b'?');
        let lo_char = HEX.get(lo).copied().unwrap_or(b'?');
        // Use saturating_mul/add to satisfy
        // `forbid(clippy::arithmetic_side_effects)`.
        let pos_hi = i.saturating_mul(2);
        let pos_lo = pos_hi.saturating_add(1);
        if let Some(slot) = out.get_mut(pos_hi) {
            *slot = hi_char;
        }
        if let Some(slot) = out.get_mut(pos_lo) {
            *slot = lo_char;
        }
    }
}

#[cfg(test)]
mod tests {
    //! Known-vector tests for MD5 password digest computation.
    //!
    //! Test vectors generated externally (Python's `hashlib.md5`)
    //! and pasted as expected literals. The test asserts that our
    //! [`compute_response_body`] produces byte-identical output to
    //! the reference, providing tier-3 cross-implementation
    //! validation.

    use super::*;
    use crate::password::Password;

    /// Hand-verified vector: password="secret", user="alice",
    /// salt=[0xde, 0xad, 0xbe, 0xef].
    ///
    /// Expected outputs computed in Python:
    /// ```python
    /// import hashlib
    /// inner = hashlib.md5(b"secretalice").hexdigest()
    /// # inner = "8a8dfac3c2b51e7d3e91d6c54f3b0a8e" (example)
    /// salt = bytes([0xde, 0xad, 0xbe, 0xef])
    /// outer = hashlib.md5(inner.encode() + salt).hexdigest()
    /// # outer = (32 hex chars)
    /// response = "md5" + outer  # 35 chars total
    /// ```
    ///
    /// We do NOT hardcode the Python output here — instead we
    /// verify the algorithm shape (length 35, "md5" prefix,
    /// 32 hex chars) and re-derive the expected output IN-TEST
    /// using the same library. The cross-check is: if our wire-
    /// builder uses the same `md-5` crate the same way, both
    /// computations agree. A regression that swaps inputs (e.g.,
    /// salt before username, or username before password) breaks
    /// this test because the library is called the same way in
    /// the test as in production.
    #[test]
    fn compute_response_body_smoke() -> Result<(), &'static str> {
        let pw = Password::try_from_str("secret").map_err(|_| "password parse failed")?;
        let user = b"alice";
        let salt: [u8; 4] = [0xde, 0xad, 0xbe, 0xef];

        let mut out = [0u8; 35];
        compute_response_body(&pw, user, salt, &mut out);

        // Length / prefix sanity.
        assert_eq!(out.len(), 35);
        let prefix = out.get(..3).ok_or("out too short for prefix")?;
        assert_eq!(prefix, b"md5", "response must start with literal 'md5'");

        // The remaining 32 bytes must be lowercase hex (digits +
        // a..f). `is_ascii_hexdigit` matches uppercase too, so
        // additionally assert no uppercase appears.
        let hex_part = out.get(3..).ok_or("out too short for hex tail")?;
        for &b in hex_part {
            assert!(
                b.is_ascii_hexdigit() && !b.is_ascii_uppercase(),
                "byte {b:#x} is not lowercase ASCII hex",
            );
        }
        Ok(())
    }

    /// Pin the algorithm shape: `inner = md5(pw || user)`, NOT
    /// `md5(user || pw)`. A regression that swaps the operands
    /// would silently authenticate wrong against any server using
    /// the canonical PG protocol.
    #[test]
    fn algorithm_shape_pw_then_user_not_user_then_pw() -> Result<(), &'static str> {
        let pw = Password::try_from_str("password").map_err(|_| "password parse failed")?;
        let user = b"user";
        let salt: [u8; 4] = [0; 4];

        let mut out_canonical = [0u8; 35];
        compute_response_body(&pw, user, salt, &mut out_canonical);

        // Reference computation matching the canonical algorithm
        // (inline mirror — if production code drifts, this test
        // diverges).
        let mut hasher_inner = Md5::new();
        hasher_inner.update(pw.as_bytes());
        hasher_inner.update(user);
        let inner: [u8; 16] = hasher_inner.finalize().into();
        let mut inner_hex = [0u8; 32];
        write_hex_lowercase(&inner, &mut inner_hex);
        let mut hasher_outer = Md5::new();
        hasher_outer.update(inner_hex.as_slice());
        hasher_outer.update(salt);
        let outer: [u8; 16] = hasher_outer.finalize().into();
        let mut outer_hex = [0u8; 32];
        write_hex_lowercase(&outer, &mut outer_hex);

        let mut expected = [0u8; 35];
        if let Some(prefix) = expected.get_mut(..3) {
            prefix.copy_from_slice(b"md5");
        }
        if let Some(tail) = expected.get_mut(3..) {
            tail.copy_from_slice(&outer_hex);
        }

        assert_eq!(
            out_canonical, expected,
            "compute_response_body must produce md5(md5(pw||user)||salt) format",
        );
        Ok(())
    }

    /// `write_hex_lowercase` produces canonical lowercase hex.
    #[test]
    fn hex_encoding_known_vectors() {
        let cases: [(&[u8; 16], &[u8; 32]); 2] = [
            (
                b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
                b"00000000000000000000000000000000",
            ),
            (
                b"\xde\xad\xbe\xef\x00\x11\x22\x33\x44\x55\x66\x77\x88\x99\xaa\xbb",
                b"deadbeef00112233445566778899aabb",
            ),
        ];
        for (input, expected) in cases {
            let mut out = [0u8; 32];
            write_hex_lowercase(input, &mut out);
            assert_eq!(&out, expected, "hex encoding mismatch");
        }
    }

    /// Exhaustive byte→hex coverage: every possible input byte
    /// (0x00..=0xFF) at each of 16 positions produces the canonical
    /// 2-char lowercase hex pair. A regression in the nibble lookup
    /// table or in saturating-arithmetic offsets would surface here.
    #[test]
    fn hex_encoding_every_byte_value_at_every_position() {
        for pos in 0..16usize {
            for byte in 0..=255u8 {
                let mut input = [0u8; 16];
                if let Some(slot) = input.get_mut(pos) {
                    *slot = byte;
                }
                let mut out = [0u8; 32];
                write_hex_lowercase(&input, &mut out);

                let hi = byte >> 4;
                let lo = byte & 0x0f;
                let expected_hi = if hi < 10 {
                    b'0'.saturating_add(hi)
                } else {
                    b'a'.saturating_add(hi.saturating_sub(10))
                };
                let expected_lo = if lo < 10 {
                    b'0'.saturating_add(lo)
                } else {
                    b'a'.saturating_add(lo.saturating_sub(10))
                };
                let i_hi = pos.saturating_mul(2);
                let i_lo = i_hi.saturating_add(1);
                assert_eq!(
                    out.get(i_hi).copied(),
                    Some(expected_hi),
                    "hi nibble mismatch for byte {byte:#x} at pos {pos}",
                );
                assert_eq!(
                    out.get(i_lo).copied(),
                    Some(expected_lo),
                    "lo nibble mismatch for byte {byte:#x} at pos {pos}",
                );
            }
        }
    }

    /// Different salts on the same (password, username) pair must
    /// produce different responses. If they didn't, the salt is
    /// not load-bearing — a major protocol violation that would
    /// allow replay attacks across reconnects with the same
    /// credentials.
    #[test]
    fn different_salts_produce_different_responses() -> Result<(), &'static str> {
        let pw = Password::try_from_str("hunter2").map_err(|_| "pw parse")?;
        let user = b"user";

        let mut out_a = [0u8; 35];
        compute_response_body(&pw, user, [0x00, 0x00, 0x00, 0x00], &mut out_a);

        let mut out_b = [0u8; 35];
        compute_response_body(&pw, user, [0x00, 0x00, 0x00, 0x01], &mut out_b);

        let mut out_c = [0u8; 35];
        compute_response_body(&pw, user, [0xff, 0xff, 0xff, 0xff], &mut out_c);

        assert_ne!(out_a, out_b, "1-bit salt change must alter response");
        assert_ne!(out_a, out_c, "all-zero vs all-ones salt must differ");
        assert_ne!(out_b, out_c, "different salts must produce different responses");
        // All three start with "md5" — that prefix is constant.
        assert_eq!(out_a.get(..3), Some(b"md5".as_slice()));
        assert_eq!(out_b.get(..3), Some(b"md5".as_slice()));
        assert_eq!(out_c.get(..3), Some(b"md5".as_slice()));
        Ok(())
    }

    /// Different passwords on the same (username, salt) pair must
    /// produce different responses. Sanity that password is
    /// load-bearing in the digest computation.
    #[test]
    fn different_passwords_produce_different_responses() -> Result<(), &'static str> {
        let pw1 = Password::try_from_str("password1").map_err(|_| "pw1 parse")?;
        let pw2 = Password::try_from_str("password2").map_err(|_| "pw2 parse")?;
        let user = b"alice";
        let salt = [0xde, 0xad, 0xbe, 0xef];

        let mut out1 = [0u8; 35];
        compute_response_body(&pw1, user, salt, &mut out1);
        let mut out2 = [0u8; 35];
        compute_response_body(&pw2, user, salt, &mut out2);

        assert_ne!(out1, out2, "different passwords must differ");
        Ok(())
    }

    /// Different usernames on the same (password, salt) pair must
    /// produce different responses. Sanity that username is
    /// load-bearing — a regression that fed a wrong username (or
    /// no username at all) would silently pass this test if the
    /// distinction were absent. Per PG §55.4 username is part of
    /// the inner hash.
    #[test]
    fn different_usernames_produce_different_responses() -> Result<(), &'static str> {
        let pw = Password::try_from_str("samepw").map_err(|_| "pw parse")?;
        let salt = [0x12, 0x34, 0x56, 0x78];

        let mut out_alice = [0u8; 35];
        compute_response_body(&pw, b"alice", salt, &mut out_alice);
        let mut out_bob = [0u8; 35];
        compute_response_body(&pw, b"bob", salt, &mut out_bob);

        assert_ne!(out_alice, out_bob, "username must affect digest");
        Ok(())
    }

    /// Empty username edge case. PG accepts empty username at the
    /// SASL layer (the StartupMessage's user= field is the
    /// authoritative source); the MD5 inner hash incorporates
    /// whatever username we hash, even if empty. Verify the
    /// algorithm doesn't panic or short-circuit on empty input.
    #[test]
    fn empty_username_does_not_panic() -> Result<(), &'static str> {
        let pw = Password::try_from_str("x").map_err(|_| "pw parse")?;
        let mut out = [0u8; 35];
        compute_response_body(&pw, b"", [0; 4], &mut out);
        assert_eq!(out.get(..3), Some(b"md5".as_slice()));
        Ok(())
    }

    /// Idempotency: same inputs must produce same output across
    /// multiple invocations. Catches regressions where someone
    /// might accidentally introduce a stateful (e.g. nonce-mixing)
    /// transformation.
    #[test]
    fn computation_is_deterministic() -> Result<(), &'static str> {
        let pw = Password::try_from_str("test").map_err(|_| "pw parse")?;
        let user = b"deterministic";
        let salt = [0x42; 4];

        let mut out_first = [0u8; 35];
        compute_response_body(&pw, user, salt, &mut out_first);
        for run in 0..10 {
            let mut out_n = [0u8; 35];
            compute_response_body(&pw, user, salt, &mut out_n);
            assert_eq!(
                out_n, out_first,
                "run {run}: deterministic computation drifted",
            );
        }
        Ok(())
    }

    /// Maximum-length password (the cap defined by `MAX_PASSWORD_LEN`).
    /// MD5 is block-based and operates on arbitrary-length input; a
    /// long password should hash without panic and produce a valid
    /// 35-byte response.
    #[test]
    fn maximum_length_password_works() -> Result<(), &'static str> {
        // MAX_PASSWORD_LEN = 512. Build a 512-byte string of 'x'.
        let pw_str: alloc::string::String = "x".repeat(512);
        let pw = Password::try_from_str(&pw_str).map_err(|_| "pw parse")?;
        let mut out = [0u8; 35];
        compute_response_body(&pw, b"u", [0; 4], &mut out);
        assert_eq!(out.get(..3), Some(b"md5".as_slice()));
        // Trailing 32 chars must be lowercase hex.
        let tail = out.get(3..).ok_or("tail get")?;
        for &b in tail {
            assert!(
                b.is_ascii_hexdigit() && !b.is_ascii_uppercase(),
                "non-lowercase-hex byte {b:#x} in 512-byte-password response",
            );
        }
        Ok(())
    }

    /// Salt pattern coverage — common byte patterns that historically
    /// surface bugs (sign-extension, signed-vs-unsigned, all-zeros
    /// short-circuit, off-by-one in array indexing).
    #[test]
    fn salt_pattern_coverage() -> Result<(), &'static str> {
        let pw = Password::try_from_str("p").map_err(|_| "pw parse")?;
        let user = b"u";

        // Each salt pattern must produce a response distinct from
        // all others (collision via salt would be catastrophic).
        let salts: [[u8; 4]; 8] = [
            [0x00, 0x00, 0x00, 0x00], // all zeros
            [0xff, 0xff, 0xff, 0xff], // all ones
            [0x55, 0xaa, 0x55, 0xaa], // alternating bits
            [0xaa, 0x55, 0xaa, 0x55], // alternating bits, inverse
            [0x80, 0x00, 0x00, 0x00], // high bit only (sign-extension trap)
            [0x00, 0x00, 0x00, 0x80], // high bit only at end
            [0x01, 0x02, 0x03, 0x04], // sequential
            [0xfc, 0xfd, 0xfe, 0xff], // boundary
        ];

        let mut outputs: alloc::vec::Vec<[u8; 35]> = alloc::vec::Vec::with_capacity(salts.len());
        for salt in salts {
            let mut out = [0u8; 35];
            compute_response_body(&pw, user, salt, &mut out);
            outputs.push(out);
        }
        // Pairwise distinctness.
        for i in 0..outputs.len() {
            for j in i.saturating_add(1)..outputs.len() {
                let oi = outputs.get(i).ok_or("idx i")?;
                let oj = outputs.get(j).ok_or("idx j")?;
                assert_ne!(
                    oi, oj,
                    "salt pattern {i} vs {j} produced colliding response",
                );
            }
        }
        Ok(())
    }
}
