//! `Pristine` invariant trait — paired with `#[derive(Pristine)]` from
//! the `bsql-pg-proto-derive` crate.
//!
//! # Purpose
//!
//! Some types in the protocol carry a **pristine state** invariant:
//! every field equals its `Default` (Options are `None`, integers are
//! `0`, etc.). This is structurally meaningful because such types
//! are referenced as `'static` constants (e.g. the `static EMPTY:
//! SessionParams` cold-fallback at `protocol::cold_session_params`)
//! where Rust **never drops** them — `ZeroizeOnDrop` chains never
//! fire on a `'static`. This is fine **iff** the type is genuinely
//! pristine (no secret-bearing field has been initialised).
//!
//! The predicate is auto-generated by `#[derive(Pristine)]`. The
//! compiler synthesises one per-field check per declared field;
//! missing a field is **structurally impossible** (the macro inspects
//! every field via `syn::Fields::Named`). Without the derive — i.e. a
//! hand-rolled `const fn is_pristine(&self) -> bool { self.f1.is_none()
//! && ... }` — adding a new field would require the contributor to
//! remember to extend the predicate, a tier-3 by-discipline risk
//! surface. Tier-1 by-construction is the only acceptable shape.
//!
//! # Two-method shape
//!
//! The derive emits BOTH:
//!
//! - **Trait impl** [`Pristine::is_pristine`] — non-`const` (Rust
//!   `const fn` in trait methods is unstable as of MSRV 1.95). For
//!   runtime polymorphic dispatch.
//! - **Inherent `__pristine_const`** — `const fn` for use in
//!   `const _: () = assert!(EMPTY.__pristine_const())` pin contexts.
//!
//! Both have identical body (per-field check conjunction).
//!
//! # Supported field types
//!
//! - `Option<T>` (any T) — emits `self.field.is_none()`.
//! - `bool` — emits `!self.field`.
//! - Integer types (u8/u16/u32/u64/u128/usize, i8/i16/i32/i64/i128/isize) — emits `self.field == 0`.
//!
//! Other types fail the derive with a clear error pointing at the
//! offending field. Hand-roll the trait impl for shapes outside the
//! supported set.
//!
//! # Cross-references
//!
//! - `crates/bsql-pg-proto/src/protocol.rs` — `static EMPTY:
//!   SessionParams = SessionParams::new()` const-asserts using
//!   `__pristine_const`.

/// Marker trait for types whose "pristine state" (every field at its
/// `Default`) is structurally meaningful — typically because the type
/// is referenced as a `'static` constant where `Drop` never fires
/// (and thus secret-bearing fields would leak for the program's
/// lifetime if non-pristine).
///
/// # Implementation
///
/// Auto-derived via `#[derive(Pristine)]` from the
/// `bsql-pg-proto-derive` pair-crate. Hand-implementing is allowed but
/// rare — the derive covers all supported field shapes.
///
/// # Sealing posture
///
/// Not sealed: external crates (Phase 2 macros, future drivers) may
/// have their own pristine-state types deserving the trait. The
/// derive remains the recommended path; manual impls follow the same
/// shape.
pub trait Pristine {
    /// Returns `true` iff every field of `self` equals its `Default`.
    ///
    /// # Trait method shape (non-const)
    ///
    /// Trait methods cannot be `const fn` on stable Rust as of
    /// MSRV 1.95. The auto-derive emits an inherent `const fn
    /// __pristine_const(&self) -> bool` alongside this trait method
    /// for compile-time pin contexts.
    ///
    /// When you need compile-time evaluation, use the inherent path:
    /// `MyType::__pristine_const(&value)` (or `value.__pristine_const()`
    /// inside a `const` block).
    fn is_pristine(&self) -> bool;
}
