[package]
name = "bsql-postgres-async"
version = "0.1.0-alpha.0"
edition = "2024"
rust-version = "1.95"
description = "Async PostgreSQL driver built on bsql-pg-proto sans-IO state machine"
license = "MIT OR Apache-2.0"

[dependencies]
bsql-postgres-core = { path = "../core" }
bsql-postgres-proto = { path = "../proto" }
tokio = { version = "1", features = ["net", "io-util", "macros", "rt", "rt-multi-thread", "time", "sync"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
