[package]
name = "bsql-postgres-sync"
version = "0.1.0-alpha.0"
edition = "2024"
rust-version = "1.95"
description = "Sync PostgreSQL driver built on bsql-pg-proto sans-IO state machine"
license = "MIT OR Apache-2.0"

[dependencies]
bsql-postgres-core = { path = "../core" }
bsql-postgres-proto = { path = "../proto" }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
webpki-roots = "0.26"
